### ISSUE TITLE
0.1.5 and 0.2.0 Incompatibility with macro re-export

### ISSUE THREAD

**Issue by konnorandrews** [danielhenrymantilla/macro_rules_attribute-rs#18]
After updating to 0.1.5 (and trying 0.2.0) I get the following from other crates using a re-exported copy of the derive macro.
```rs
error[E0433]: failed to resolve: could not find `macro_rules_attribute` in the list of imported crates
  --> [redacted]
   |
14 | #[derive(Patch!, Serialize, Deserialize, Clone, Debug)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `macro_rules_attribute` in the list of imported crates
   |
   = note: this error originates in the attribute macro `derive` (in Nightly builds, run with -Z macro-backtrace for more info)
 ```
 
In my crate I have the following in the root module (lib.rs).
```rs
pub use macro_rules_attribute::derive;
```
In my other crates I am using it like this
```rs
use config::{derive, Patch};

#[derive(Patch!, Serialize, Deserialize, Clone, Debug)]
pub struct Params {
    ...
}
```

Version 0.1.3 works with this pattern.

**Comment by danielhenrymantilla** [comment]
Thanks for the report; I've yanked `0.1.5` in response to this. Will look into making `0.2+` work with this, and that way maybe I can offer a "convenience post-yank landing pad for `0.1+` users
